#include "vivstd.h"

#include "../demo/ArithmeticOperators.c"
#include "../demo/Array.c"
#include "../demo/Array2D.c"
#include "../demo/ArrayPointer.c"
#include "../demo/CallByValue.c"
#include "../demo/CharArrayPointer.c"
#include "../demo/CopyMemory.c"
#include "../demo/DataStruct.c"
#include "../demo/DataType.c"
#include "../demo/Files.c"
#include "../demo/Function.c"
#include "../demo/Iterator.c"
#include "../demo/Jisikin.c"
#include "../demo/MallocMemset.c"
#include "../demo/Math.c"
#include "../demo/Operator.c"
#include "../demo/PointerArray.c"
#include "../demo/Pointers.c"
#include "../demo/Printf.c"
#include "../demo/Recursion.c"
#include "../demo/Scanf.c"
#include "../demo/Variable.c"
#include "../demo/CallByPointer.c"
#include "../demo/WhileLoop.c"
#include "../demo/ArrayShift.c"
#include "../demo/Struct.c"
#include "../demo/Database.c"
#include "../demo/BinarySearchTree.c"
#include "../demo/Fibo.c"
#include "../demo/NumberReal.c"
#include "../demo/Calculate.c"

void PrintMenu();
void Exec(int choice);
void Printf();
void PointerArray();
void PointerInt();
void DataType();
void ArithmeticOperators();
void Scanf();
void Math();
void Function();
void Operator();
void Array();
void Array2D();
void Files(bool rw, char *message);
void Recursion();
void DataStruct();
void ArrayPointer();
void MallocMemset();
void CopyMemory();
void CharArrayPointer();
void CallByValue();
void CallByPointer();
void WhileLoop();
void ArrayShift();
void Struct();
void Database();
void BinarySearchTree();
void FiboStart();
void NumberReal();
void Calculate();
